import { parseUri } from "@walletconnect/utils";
import Head from "next/head";
import { useState } from "react";
import QrReader from "../components/QrReader";
import { createLegacySignClient } from '../utils/LegacyWalletConnectUtil';
import { signClient } from "../utils/WalletConnectUtil";

export default function Home() {
  const [uri, setUri] = useState("");
  const [loading, setLoading] = useState(false);
  async function onConnect(uri: string) {
    try {
      setLoading(true);
      const { version } = parseUri(uri);

      // Route the provided URI to the v1 SignClient if URI version indicates it, else use v2.
      if (version === 1) {
        createLegacySignClient({ uri })
      } else {
        await signClient.pair({ uri });
      }
    } catch (err: unknown) {
      alert(err);
    } finally {
      setUri("");
      setLoading(false);
    }
  }
  return (
    <div>
      <Head>
        <title>Soika</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-2/3 mx-auto">
        <div className="max-w-lg p-4 shadow-md text-gray-100 mx-auto mt-6">
          <div className="space-y-4">
            <div className="space-y-2">
              <div className="flex justify-center object-cover object-center w-full rounded-md h-72 bg-gray-500">
                <QrReader onConnect={onConnect} />
              </div>
            </div>
            <div className="space-y-2">
              <a rel="noopener noreferrer" href="#" className="block">
                <h3 className="text-xl font-semibold text-yellow-400">
                  Please scan the QR Code
                </h3>
              </a>
              <p className="leading-snug text-gray-400">
                That allows us to scan the transaction destination and try to
                warn you against mistakes or potential danger.
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
